language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm test -- u --coverage --coverageReporters=text-lcov | coveralls

after_success:
  - npm run coveralls