export const FETCHMENU = 'FETCHMENU'
export const POSTMENU = 'POSTMENU'
export const REGISTER = 'REGISTER'
export const LOGIN = 'LOGIN'
export const BASEURL = 'https://fast-food-fast-db.herokuapp.com/api/v1'